### ISSUE TITLE
源码效果与npm下载导入的不一样

### ISSUE THREAD

**Issue by MoJingYan** [cz2542079957/vue-activity-calendar#1]
源码效果与npm下载导入的不一样，出入较大，是否是因为代码未提交？

**Comment by JustinChen719** [comment]
你好，很感谢你的使用，请问是哪里出现了问题？源码中开始使用ts写的，后来考虑到有人拉取源码来使用，使用ts可能会给他们带来问题，所以改成原始js的写法了。npm中的资源是转译后的纯js代码。现在可以确认的是两个平台的代码发布版本是一致的，如果有问题有可能是我没有完全把ts改成js代码，或者是有其他的问题也请你发现后告知我，我会改进，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cz2542079957/vue-activity-calendar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 下午3:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cz2542079957/vue-activity-calendar] 源码效果与npm下载导入的不一样 (Issue #1)





 
源码效果与npm下载导入的不一样，出入较大，是否是因为代码未提交？

**Comment by JustinChen719** [comment]
你好，我检查了两边的代码，确实在github上的代码文件存在缺失，我刚刚发布的1.2.2版顺便解决了该问题，感谢使用。

**Comment by MoJingYan** [comment]
十分感谢大佬
